# Generated by Django 3.2 on 2022-11-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20221122_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthActivityLog',
        ),
    ]
